#!/bin/bash
# 功能：自动生成order.txt内容，按时间顺序
# 使用说明：
#     自动：
#         cp order.sh .git/hooks/pre-commit  每次提交自动更新order.txt文件。
#     手动：
#         ./order.sh 手动更新order文件
    
#当前脚本目录
CURRDIR=$(pwd)


if [[ ${CURRDIR} =~ sql/.git/hooks$ ]]; then
    TARGETDIR="${CURRDIR}/../../"
    cd ${TARGETDIR}
elif [[ ${CURRDIR} =~ sql$ ]];then
    echo ${CURRDIR}
else
    echo "脚本所在路径错误，请确认!!!"
    exit
fi

#项目目录
PROJECTDIR="$(pwd)/gsn_mcenter"

#分支目录
WORKPROJECT="${PROJECTDIR}/master"

#版本地址
ORDERFLE="${WORKPROJECT}/order.txt"

#忽略文件
IGNOREFILES=("order.txt" "readme.txt")

#清空文件
cat  /dev/null > ${ORDERFLE} 

if [ ! -e ${ORDERFLE} ]; then 
    touch ${ORDERFLE}
fi


#切换到sql文件目录、遍历文件、写入文件、返回当前目录
cd $WORKPROJECT
for file in `ls  *.sql |sort -n -k 3 -t _`; do
    isIgnore=0
    for igfile in ${IGNOREFILES[*]}; do
        if [ $file == $igfile ]; then
            echo "忽略文件${file}"
            isIgnore=1
        fi
    done
    if [ ${isIgnore} -ne 1 ]; then
           echo ${file} >> ${ORDERFLE}
    fi
done
cd -

git add ${ORDERFLE}